[package]
name = "hello_erc20" # the name of the package
version = "0.1.0"    # the current version, obeying semver
edition = "2023_10"

[dependencies]
starknet = ">=2.1.0"

[[target.starknet-contract]]
allowed-libfuncs = true