[package]
name = "helloERC20" # the name of the package
version = "0.1.0"    # the current version, obeying semver

[[target.starknet-contract]]

[tool.nile_rs]
artifacts_dir = "./target/release"
contracts_dir = "./src"
